homework_00:
  image: data/cherubino.jpg   
  point: [300, 500]           
  color: [255, 0, 0]          
  radius: 50                  
  
homework_01:
  delay: 30
  symbol: "q"
  radius: 5
  black: [0, 0, 0]
  height: 360
  width: 680
  procent: 100
  color_size: 255
  hue_board: 180
  window_name: "Image"
  augmented_name: "ColorJitter"
  alpha_range: [0, 360]
  beta_range: [0, 1]
  gamma_range: [0, 1]
  delta_range: [0, 1]

homework_02:
  image: ../data/saturn_rings.png
  delay: 30
  symbol: "q"
  procent: 100
  color_size: 255
  window_name: "Image"
  spectr_name: "Spectr"
  height_range: [0, 1]
  width_range: [0, 1]

homework_03:
  input_image_path: ../data/puppy.png
  output_image_path: ../data/output.png
  opencv_output_image_path: ../data/cv_output.png
  sigma_space: 15
  sigma_color: 15

homework_04:
  # Input image
  input_image: ../data/building.png
  # Marr-Hildreth edge detection
  sigma: 3.5 
  thresh_percent: 0.2 # T = thresh_percent * LoG.max()
  # RANSAC
  threshold: 5
  max_trials: 5000
  seed: 0xC0FFEE
  # Output images
  output_image: ../data/line_ransac.jpg
  output_edges: ../data/marr_hildreth_edges.jpg
  color_size: 255
  color: [255, 0, 255]
  radius: 2
  line_thickness: 3
