homework_00:
  image: data/cherubino.jpg   
  point: [300, 500]           
  color: [255, 0, 0]          
  radius: 50                  
  
homework_01:
  delay: 30
  symbol: "q"
  radius: 5
  black: [0, 0, 0]
  height: 360
  width: 680
  procent: 100
  color_size: 255
  hue_board: 180
  window_name: "Image"
  augmented_name: "ColorJitter"
  alpha_range: [0, 360]
  beta_range: [0, 1]
  gamma_range: [0, 1]
  delta_range: [0, 1]

homework_02:
  image: ../data/saturn_rings.png
  delay: 30
  symbol: "q"
  procent: 100
  color_size: 255
  window_name: "Image"
  spectr_name: "Spectr"
  height_range: [0, 1]
  width_range: [0, 1]
